version: '3.9'

services:
  mysql:
    image: mysql/mysql-server
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd     # Set the root password
      MYSQL_DATABASE: userdata                     # Database name
      MYSQL_USER: user123                        # Your MySQL username
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3306"                                  # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql                    # Persist MySQL data
      - ./sql:/docker-entrypoint-initdb.d            # Mount SQL scripts directory

  app:
    build:
      context: .                                     # Path to your Dockerfile
      dockerfile: Dockerfile                         # Specify the Dockerfile
    container_name: java_app_container
    volumes:
     - C:/Users/ishwa/eclipse-new-workspace/Training/AdvancedJava/logs:/logs
    ports:
      - "9090:8080"                                  # Expose your app's port
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/userdata  # JDBC URL for MySQL
      #JDBC_URL: jdbc:mysql://localhost:3306/advancedjavatraining
      JDBC_USERNAME: user123	                  # MySQL username
      JDBC_PASSWORD: mysql                      # MySQL password
    depends_on:
      - mysql                                           # Wait for MySQL to start
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Configuration file for Prometheus
    ports:	
      - "9091:9090"  # Expose Prometheus on port 9091
    depends_on:
      - app
  
  loki:
    image: grafana/loki:latest	
    container_name: loki
    ports:
      - "3100:3100"	
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-wal:/wal
      - ./loki-config.yaml:/etc/loki/local-config.yaml
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:	
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock  # Read Docker container logs
      - C:/Users/ishwa/eclipse-new-workspace/Training/AdvancedJava/logs:/logs
    command: -config.file=/etc/promtail/config.yaml -log.level=debug
    depends_on:
      - loki
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"  # Expose Grafana port
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set admin password
    depends_on:
      - prometheus  # Wait for Prometheus to start
      - loki

volumes:
  mysql_data:                                           # Volume to persist MySQL data
