auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  wal:
     enabled: true
     dir: /tmp/loki-wal
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb  
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb:
    directory: /loki/index  # Directory for index files

  filesystem:
    directory: /loki/chunks  # Directory for chunk storage

limits_config:
  allow_structured_metadata: false

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
