server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:	
  - job_name: java_app_logs
    static_configs:
      - targets:
          - localhost
        labels:	
          job: java_application
          __path__: /logs/*.log


  
#    pipeline_stages:
#      - json:
#          expressions:
#            log: log
#      - match:
#          selector: '{job="java-application"}'
#          stages:
#            - drop:
#                expression: 'level != "INFO" && level != "ERROR"'
#            - drop:
#                expression: 'source != "com.example.MyClass"'